In [ ]:
"""
---  -  COMPARE DATA STORAGE  -  ----

Code from 
YT :

Medallion Data Science
5,82 k abonnés

The BEST way to store data in python & pandas.. spoiler: it's not CSV

https://www.youtube.com/watch?v=u4rsA5ZiTls&t=74s
https://www.youtube.com/watch?v=u4rsA5ZiTls&t=74s

"""

In [1]:
pip install pyarrow

Collecting pyarrowNote: you may need to restart the kernel to use updated packages.
  Downloading pyarrow-8.0.0-cp37-cp37m-win_amd64.whl (17.8 MB)
Requirement already satisfied: numpy>=1.16.6 in c:\users\user\miniconda3\lib\site-packages (from pyarrow) (1.21.4)
Installing collected packages: pyarrow
Successfully installed pyarrow-8.0.0

In [2]:
pip install fastparquet

Collecting fastparquet
  Downloading fastparquet-0.8.1-cp37-cp37m-win_amd64.whl (611 kB)
Collecting cramjam>=2.3.0
  Downloading cramjam-2.5.0-cp37-none-win_amd64.whl (993 kB)
Collecting fsspec
  Downloading fsspec-2022.5.0-py3-none-any.whl (140 kB)
Requirement already satisfied: numpy>=1.18 in c:\users\user\miniconda3\lib\site-packages (from fastparquet) (1.21.4)
Requirement already satisfied: pandas>=1.1.0 in c:\users\user\miniconda3\lib\site-packages (from fastparquet) (1.3.4)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\user\miniconda3\lib\site-packages (from pandas>=1.1.0->fastparquet) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in c:\users\user\miniconda3\lib\site-packages (from pandas>=1.1.0->fastparquet) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\user\miniconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=1.1.0->fastparquet) (1.16.0)
Installing collected packages: fsspec, cramjam, fastparquet
Successfully installed cramjam-2.5.0 fastparquet-0.8.1 fsspec-2022.5.0
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# pandas-data-storage-compare.py
# pandas-data-storage-compare.py
# pandas-data-storage-compare.py

import pandas as pd
import numpy as np

def get_dataset(size):
    # Create Fake Dataset
    df = pd.DataFrame()
    df['size'] = np.random.choice(['big','medium','small'], size)
    df['age'] = np.random.randint(1, 50, size)
    df['team'] = np.random.choice(['red','blue','yellow','green'], size)
    df['win'] = np.random.choice(['yes','no'], size)
    dates = pd.date_range('2020-01-01', '2022-12-31')
    df['date'] = np.random.choice(dates, size)
    df['prob'] = np.random.uniform(0, 1, size)
    return df

def set_dtypes(df):
    df['size'] = df['size'].astype('category')
    df['team'] = df['team'].astype('category')
    df['age'] = df['age'].astype('int16')
    df['win'] = df['win'].map({'yes':True, 'no': False})
    df['prob'] = df['prob'].astype('float32')
    return df
#. print('Reading and writing CSV')
#. df = get_dataset(5_000_000)
#. df = set_dtypes(df)
#. %time df.to_csv('test.csv')
#. %time df_csv = pd.read_csv('test.csv')

# print('Reading and writing Pickle')
# df = get_dataset(5_000_000)
# df = set_dtypes(df)
# %time df.to_pickle('test.pickle')
# %time df_pickle = pd.read_pickle('test.pickle')

print('Reading and writing Parquet')
df = get_dataset(5_000_000)
df = set_dtypes(df)
%time df.to_parquet('test.parquet')
%time df_parquet = pd.read_parquet('test.parquet')

print('Reading and writing Feather')
df = get_dataset(5_000_000)
df = set_dtypes(df)
%time df.to_feather('test.feather')
%time df_feather = pd.read_feather('test.feather')

print('Reading and writing np (NP) format')
df = get_dataset(5_000_000)
df = set_dtypes(df)
%time np.save("test_save_np_format.npy", df)
%time a= np.load("test_save_np_format.npy")

In [15]:
print('Reading and writing Pickle')
df = get_dataset(5_000_000)
df = set_dtypes(df)
%time df.to_pickle('test.pickle')
%time df_pickle = pd.read_pickle('test.pickle')

Reading and writing Pickle
Wall time: 234 ms
Wall time: 172 ms

In [6]:
print('Reading and writing np (NP) format')
df = get_dataset(5_000_000)
df = set_dtypes(df)
# %time np.save("test_save_np_format.npy", df)
# %time a= np.load("test_save_np_format.npy")

np.save("test_save_np_format.npy", df)
a= np.load("test_save_np_format.npy")

Reading and writing np (NP) format

ValueError: Object arrays cannot be loaded when allow_pickle=False

In [1]:
!ls -GFlash test.csv test.pickle test.parquet test.father

'ls' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.

In [ ]:
"""
   -----    SPEED UP 2500 X   ----------
Code from 
YT :

Medallion Data Science
5,82 k abonnés

Speed up slow pandas python code by 2500x

https://www.youtube.com/watch?v=SAFmrTnEHLg
https://www.youtube.com/watch?v=SAFmrTnEHLg
"""

In [ ]:
"""
THE PROBLEME :
Reward calculation :

If they were in bed for more than 5h AND sleeping for more than 50% then, give Favorite_food.

If they have over 90 years old , give Favorite_food regardless.

Otherwise give Hate_food.

"""

In [44]:
import pandas as pd
import numpy as np

def get_data(size = 10_000_000):
    # Create Fake Dataset
    df = pd.DataFrame()
    df['age'] = np.random.randint(1, 100, size)
    df['time_in_bed'] = np.random.randint(1, 9, size)
    df['pct_sleeping'] = np.random.rand(size)    
    df['Favorite_food'] = np.random.choice(['pizza','taco','ice-cream'], size)
    df['Hate_food'] = np.random.choice(['brocoli','candy corn','eggs'], size)
    return df

In [45]:
df= get_data()

In [64]:
mask_1 = ((df['pct_sleeping'] > 0.5) & (df['time_in_bed'] > 5)) | (df['age'] > 90)
mask_2 = (df['age'] < 20)

In [67]:
df['reward'] = df['Hate_food']
# df.loc[((df['pct_sleeping'] > 0.5) & (df['time_in_bed'] > 5)) | (df['age'] > 90), 'reward'] = df['Favorite_food']
df.loc[mask_1, 'reward'] = df['Favorite_food']
df.loc[mask_2, 'reward'] = "yes teenage"

In [68]:
df

         age  time_in_bed  pct_sleeping Favorite_food   Hate_food       reward
0         75            8      0.640297         pizza     brocoli        pizza
1         57            2      0.448520          taco        eggs         eggs
2          5            4      0.215279         pizza        eggs  yes teenage
3         82            4      0.630005     ice-cream     brocoli      brocoli
4         18            6      0.108221     ice-cream     brocoli  yes teenage
...      ...          ...           ...           ...         ...          ...
3999995   22            6      0.361735     ice-cream  candy corn   candy corn
3999996   24            4      0.866098         pizza        eggs         eggs
3999997   79            1      0.014540     ice-cream     brocoli      brocoli
3999998   59            6      0.266445         pizza     brocoli      brocoli
3999999   51            2      0.788435     ice-cream        eggs         eggs

[4000000 rows x 6 columns]

In [57]:
# level 4 - np where  -  make the same job.
# %% timeit 
df = get_data(10_000)
df = get_data(4_000_000)
df['reward'] = np.where(((df['pct_sleeping'] > 0.5) & (df['time_in_bed'] > 5))
                        | (df['age'] > 90), 
                        df['Favorite_food'], 
                        df['Hate_food'])

In [58]:
df

         age  time_in_bed  pct_sleeping Favorite_food   Hate_food      reward
0         75            8      0.640297         pizza     brocoli       pizza
1         57            2      0.448520          taco        eggs        eggs
2          5            4      0.215279         pizza        eggs        eggs
3         82            4      0.630005     ice-cream     brocoli     brocoli
4         18            6      0.108221     ice-cream     brocoli     brocoli
...      ...          ...           ...           ...         ...         ...
3999995   22            6      0.361735     ice-cream  candy corn  candy corn
3999996   24            4      0.866098         pizza        eggs        eggs
3999997   79            1      0.014540     ice-cream     brocoli     brocoli
3999998   59            6      0.266445         pizza     brocoli     brocoli
3999999   51            2      0.788435     ice-cream        eggs        eggs

[4000000 rows x 6 columns]